{{
    config(
        unique_key='lga_code',
        alias='dim_lga'
    )
}}

with source  as (

    select * from {{ ref('b_lga_g01') }}

),

join_g02 as (
    select s.*,
    g02.median_age_persons as median_age_persons,
    g02.median_mortgage_repay_monthly as median_mortgage_repay_monthly,
    g02.median_tot_prsnl_inc_weekly as median_tot_prsnl_inc_weekly,
    g02.median_rent_weekly as median_rent_weekly,
    g02.median_tot_fam_inc_weekly as median_tot_fam_inc_weekly,
    g02.average_num_psns_per_bedroom as average_num_psns_per_bedroom,
    g02.median_tot_hhd_inc_weekly as median_tot_hhd_inc_weekly,
    g02.average_household_size as average_household_size
    from source s 
    Left join {{ ref('b_lga_g02') }} g02 on s.lga_code_2016 = g02.lga_code_2016
),

join_lga_code as (
    select 
        RIGHT(LGA_CODE_2016, 5) as lga_code,
        lower(lga.lga_name) as lga_name,
        Tot_P_M,
        Tot_P_F,
        Tot_P_P,
        Age_0_4_yr_M,
        Age_0_4_yr_F,
        Age_0_4_yr_P,
        Age_5_14_yr_M,
        Age_5_14_yr_F,
        Age_5_14_yr_P,
        Age_15_19_yr_M,
        Age_15_19_yr_F,
        Age_15_19_yr_P,
        Age_20_24_yr_M,
        Age_20_24_yr_F,
        Age_20_24_yr_P,
        Age_25_34_yr_M,
        Age_25_34_yr_F,
        Age_25_34_yr_P,
        Age_35_44_yr_M,
        Age_35_44_yr_F,
        Age_35_44_yr_P,
        Age_45_54_yr_M,
        Age_45_54_yr_F,
        Age_45_54_yr_P,
        Age_55_64_yr_M,
        Age_55_64_yr_F,
        Age_55_64_yr_P,
        Age_65_74_yr_M,
        Age_65_74_yr_F,
        Age_65_74_yr_P,
        Age_75_84_yr_M,
        Age_75_84_yr_F,
        Age_75_84_yr_P,
        Age_85ov_M,
        Age_85ov_F,
        Age_85ov_P,
        Counted_Census_Night_home_M,
        Counted_Census_Night_home_F,
        Counted_Census_Night_home_P,
        Count_Census_Nt_Ewhere_Aust_M,
        Count_Census_Nt_Ewhere_Aust_F,
        Count_Census_Nt_Ewhere_Aust_P,
        Indigenous_psns_Aboriginal_M,
        Indigenous_psns_Aboriginal_F,
        Indigenous_psns_Aboriginal_P,
        Indig_psns_Torres_Strait_Is_M,
        Indig_psns_Torres_Strait_Is_F,
        Indig_psns_Torres_Strait_Is_P,
        Indig_Bth_Abor_Torres_St_Is_M,
        Indig_Bth_Abor_Torres_St_Is_F,
        Indig_Bth_Abor_Torres_St_Is_P,
        Indigenous_P_Tot_M,
        Indigenous_P_Tot_F,
        Indigenous_P_Tot_P,
        Birthplace_Australia_M,
        Birthplace_Australia_F,
        Birthplace_Australia_P,
        Birthplace_Elsewhere_M,
        Birthplace_Elsewhere_F,
        Birthplace_Elsewhere_P,
        Lang_spoken_home_Eng_only_M,
        Lang_spoken_home_Eng_only_F,
        Lang_spoken_home_Eng_only_P,
        Lang_spoken_home_Oth_Lang_M,
        Lang_spoken_home_Oth_Lang_F,
        Lang_spoken_home_Oth_Lang_P,
        Australian_citizen_M,
        Australian_citizen_F,
        Australian_citizen_P,
        Age_psns_att_educ_inst_0_4_M,
        Age_psns_att_educ_inst_0_4_F,
        Age_psns_att_educ_inst_0_4_P,
        Age_psns_att_educ_inst_5_14_M,
        Age_psns_att_educ_inst_5_14_F,
        Age_psns_att_educ_inst_5_14_P,
        Age_psns_att_edu_inst_15_19_M,
        Age_psns_att_edu_inst_15_19_F,
        Age_psns_att_edu_inst_15_19_P,
        Age_psns_att_edu_inst_20_24_M,
        Age_psns_att_edu_inst_20_24_F,
        Age_psns_att_edu_inst_20_24_P,
        Age_psns_att_edu_inst_25_ov_M,
        Age_psns_att_edu_inst_25_ov_F,
        Age_psns_att_edu_inst_25_ov_P,
        High_yr_schl_comp_Yr_12_eq_M,
        High_yr_schl_comp_Yr_12_eq_F,
        High_yr_schl_comp_Yr_12_eq_P,
        High_yr_schl_comp_Yr_11_eq_M,
        High_yr_schl_comp_Yr_11_eq_F,
        High_yr_schl_comp_Yr_11_eq_P,
        High_yr_schl_comp_Yr_10_eq_M,
        High_yr_schl_comp_Yr_10_eq_F,
        High_yr_schl_comp_Yr_10_eq_P,
        High_yr_schl_comp_Yr_9_eq_M,
        High_yr_schl_comp_Yr_9_eq_F,
        High_yr_schl_comp_Yr_9_eq_P,
        High_yr_schl_comp_Yr_8_belw_M,
        High_yr_schl_comp_Yr_8_belw_F,
        High_yr_schl_comp_Yr_8_belw_P,
        High_yr_schl_comp_D_n_g_sch_M,
        High_yr_schl_comp_D_n_g_sch_F,
        High_yr_schl_comp_D_n_g_sch_P,
        Count_psns_occ_priv_dwgs_M,
        Count_psns_occ_priv_dwgs_F,
        Count_psns_occ_priv_dwgs_P,
        Count_Persons_other_dwgs_M,
        Count_Persons_other_dwgs_F,
        Count_Persons_other_dwgs_P,
        median_age_persons,
        median_mortgage_repay_monthly,
        median_tot_prsnl_inc_weekly,
        median_rent_weekly,
        median_tot_fam_inc_weekly,
        average_num_psns_per_bedroom,
        median_tot_hhd_inc_weekly,
        average_household_size 
    from join_g02 jg
    left join {{ ref('b_lga_code') }} lga on RIGHT(jg.LGA_CODE_2016, 5) = CAST(lga.lga_code AS TEXT)
)

select * from join_lga_code